"""empty message

Revision ID: 008b0f92e199
Revises: 
Create Date: 2023-07-17 08:58:25.916870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008b0f92e199'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('associator_id', sa.Integer(), nullable=True),
    sa.Column('associated_id', sa.Integer(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['associated_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['associator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=140), nullable=True))
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=140),
               existing_nullable=True)
        batch_op.drop_column('image_url')

    op.drop_table('association')
    # ### end Alembic commands ###
